jobs:
- name: publish
  plan:
  - get: source-code
    trigger: true
  - get: docker-image-resource-source-code
  - put: master
    params:
      build: source-code
    get_params:
      save: true
  - task: test
    privileged: true
    # private registry is flaky
    attempts: 2
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: alpine
      inputs:
      - name: source-code
      - name: docker-image-resource-source-code
      - name: master
      caches:
      - path: cache/apk
      - path: cache/npm
      params:
        TEST_RUNNER: docker
        TEST_REGISTRY: ((test.registry))
        CORRECT_CREDENTIALS: ((test.credentials_good))
        INCORRECT_CREDENTIALS: ((test.credentials_bad))
        NEXUS_WORKAROUND: true
        NORMRF: true
        DOCKER_IMAGE: unit-under-test
      run:
        path: sh
        args:
        - -ec
        - |
          export NPM_CONFIG_CACHE=$PWD/cache/npm
          apt-get update
          apt-get install docker.io
          apk --update --cache-dir $PWD/cache/apk --no-progress add docker

          . docker-image-resource-source-code/assets/common.sh
          sanitize_cgroups
          start_docker 3 3

          docker load -i "master/image"
          docker tag $(cat "master/image-id") $DOCKER_IMAGE

          cd source-code/test
          npm install
          npm test
  - put: latest
    params:
      load: master
    get_params:
      skip_download: true
resources:
- name: source-code
  type: git
  webhook_token: ((webhook_token))
  source:
    uri: https://github.com/timotto/concourse-npm-resource.git
- name: docker-image-resource-source-code
  type: git
  source:
    uri: https://github.com/concourse/docker-image-resource.git
- name: master
  type: docker-image
  check_every: 24h
  source:
    repository: timotto/concourse-npm-resource
    tag: master
    username: ((dockerhub.username))
    password: ((dockerhub.password))
- name: latest
  type: docker-image
  source:
    repository: timotto/concourse-npm-resource
    tag: latest
    username: ((dockerhub.username))
    password: ((dockerhub.password))
